services:
  app:
    build: .
    container_name: fastify-app
    ports:
      - "3000:3000"
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
